const AUDIT_EVENTS = {
  USER_CREATED: 'USER_CREATED',
  USER_LOGIN: 'USER_LOGIN',
  EMAIL_LOGIN: 'EMAIL_LOGIN',
  PHONE_LOGIN: 'PHONE_LOGIN',
  GOOGLE_LOGIN: 'GOOGLE_LOGIN',
  SUBSCRIPTION_ACTIVATED: 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',
  SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  SECURITY_EVENT: 'SECURITY_EVENT',
};

module.exports = AUDIT_EVENTS;
